server:
  port: 8084

spring:
  application:
    name: user-service

#  security:
#    oauth2:
#      client:
#        registration:
#          keycloak:
#            authorization-grant-type: client_credentials
#            client-id: backend
#            client-secret: Ts9XSss1RzUpfO4n99O6REL1ALhOvtRH
#        provider:
#          keycloak:
#            token-uri: http://keycloak:8080/realms/reino-para-auth-serv-serv/protocol/openid-connect/token

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
    enabled: false
